import type { DecisionMoment } from './types';

const now = () => new Date().toISOString();

export const CURATED_DEMO_MOMENTS: DecisionMoment[] = [
  {
    id: 'moment-gym-swipe',
    kind: 'payment',
    title: 'About to pay for another gym membership',
    description: 'A demo payment intent signal shows a fresh recurring charge right before signup.',
    userId: 'demo:alex',
    source: 'demo',
    timestamp: now(),
    policyIntent: 'protect',
    transaction: {
      merchantName: 'Crunch Fitness',
      amount: 79,
      currency: 'USD',
      category: 'gym',
      status: 'pending',
      source: 'demo',
      note: 'Monthly membership checkout detected before card swipe.',
    },
    location: {
      placeName: 'Crunch Fitness · SoMa',
      latitude: 37.7819,
      longitude: -122.4056,
      distanceMeters: 180,
      source: 'demo',
      permission: 'synthetic',
    },
    signalSummary: ['Demo payment intent', 'Nearby gym', 'Two short-lived memberships in history'],
    likelyScenarioIds: ['W1_GHOST_GYM'],
  },
  {
    id: 'moment-friend-warning',
    kind: 'restaurant',
    title: 'Near a restaurant friends disliked',
    description: 'Location signal lines up with a place the user’s own circle rated badly.',
    userId: 'demo:jordan',
    source: 'demo',
    timestamp: now(),
    policyIntent: 'protect',
    location: {
      placeName: 'Tava Indian Kitchen',
      latitude: 37.4454,
      longitude: -122.1619,
      distanceMeters: 110,
      source: 'demo',
      permission: 'synthetic',
    },
    signalSummary: ['Nearby restaurant', 'Friend ratings under 3.0', 'Dinner decision right now'],
    likelyScenarioIds: ['W4_FRIEND_WARNING', 'W5_BETTER_RESTAURANT'],
  },
  {
    id: 'moment-dormant-goal',
    kind: 'health',
    title: 'Near a place that matches a dormant goal',
    description: 'A stored search and a nearby store line up with a goal the user has not followed through on.',
    userId: 'demo:sam',
    source: 'demo',
    timestamp: now(),
    policyIntent: 'nudge',
    location: {
      placeName: 'Fleet Feet',
      latitude: 37.4523,
      longitude: -122.1817,
      distanceMeters: 220,
      source: 'demo',
      permission: 'synthetic',
    },
    transaction: {
      merchantName: 'Fleet Feet',
      amount: 165,
      currency: 'USD',
      category: 'footwear',
      status: 'pending',
      source: 'demo',
      note: 'Demo purchase decision detected near running gear checkout.',
    },
    signalSummary: ['Dormant search', 'Running goal', 'Store nearby'],
    likelyScenarioIds: ['P2_DORMANT_INTEREST', 'P4_HEALTH_GOAL'],
  },
  {
    id: 'moment-repeat-regret',
    kind: 'payment',
    title: 'About to buy a product they usually regret',
    description: 'A demo checkout signal matches a pattern of returned or abandoned purchases in the same category.',
    userId: 'demo:maya',
    source: 'demo',
    timestamp: now(),
    policyIntent: 'protect',
    transaction: {
      merchantName: 'Apple Store',
      amount: 329,
      currency: 'USD',
      category: 'electronics',
      status: 'pending',
      source: 'demo',
      note: 'Demo checkout signal triggered for another audio accessory purchase.',
    },
    location: {
      placeName: 'Apple Store',
      latitude: 37.7857,
      longitude: -122.4061,
      distanceMeters: 90,
      source: 'demo',
      permission: 'synthetic',
    },
    signalSummary: ['Payment moment', 'Repeated abandoned category', 'Nearby electronics store'],
    likelyScenarioIds: ['W3_REPEAT_REGRET', 'W6_SIMILAR_DISAPPOINTMENT'],
  },
  {
    id: 'moment-subscription-bleed',
    kind: 'subscription',
    title: 'Unused subscriptions quietly draining money',
    description: 'A renewal moment surfaces recurring charges that have gone stale for weeks.',
    userId: 'demo:leo',
    source: 'demo',
    timestamp: now(),
    policyIntent: 'protect',
    transaction: {
      merchantName: 'Multiple renewals',
      amount: 58,
      currency: 'USD',
      category: 'subscription',
      status: 'pending',
      source: 'demo',
      note: 'Demo renewal bundle detected across three underused subscriptions.',
    },
    signalSummary: ['Recurring charges today', 'Three stale subscriptions', 'No recent usage'],
    likelyScenarioIds: ['W2_GHOST_SUBSCRIPTION'],
  },
];
